In [23]:
import pandas as pd
from math import sin, cos, sqrt, atan2,radians

In [30]:
df = pd.read_csv('data/charities')

In [32]:
df.head()

,Unnamed: 0,sup_type,name,address_street,city,postcode,lat,long,website,email,...,supplier_contact_email,supplier_contact_telephone,percent_recyclablenum,percent_efwnum,provides_a_rebateyn,supplier_auditislist_yes_no_na,supplier_audit_date_completed,notes,hierarchy,origin
0,307,Charity,Emmaus Greenwich,"Emmaus Greenwich Charity, 9 Knight's Hill, Wes...",London,SE27 0JD,51.431235,-0.104498,https://www.emmaus.org.uk/lambeth,giorgio@emmausgreenwich.org,...,giorgio@emmausgreenwich.org,NaN,100.0,NaN,0.0,NaN,NaN,NaN,NaN,df2
1,323,Charity,Forces Support,50-54 High Street,London,CR0 1YB,51.372522,-0.100617,NaN,croydon@forcessupport.uk,...,croydon@forcessupport.uk,NaN,100.0,0.0,0.0,NaN,NaN,NaN,NaN,df2
2,324,Charity,Furnistore,34 Holmethorpe Avenue,Redhill,RH1 2NL,51.249863,-0.157649,NaN,manager@furnistore.co.uk,...,NaN,NaN,100.0,NaN,0.0,NaN,NaN,NaN,NaN,df2
3,325,Charity,Help for Heroes,Tedworth House,Wiltshire,SP9 7AJ,51.226805,-1.668053,www.helpforheroes.co.uk,lauren.hinton@helpforheroes.org.uk,...,NaN,NaN,100.0,NaN,0.0,NaN,NaN,NaN,NaN,df2
4,326,Charity,D.A.D.S,"161-163 Longford Road, Cannock",Staffordshire,WS11 0LF,52.681517,-2.037499,NaN,andy@dadssupported.co.uk,...,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,df2

In [29]:
newlat=39.53
newlon=-119.81



#Distance function between two lat/lon
def getDist(lat1,lon1,lat2,lon2):
  R = 6373.0

  lat1 = radians(lat1)
  lon1 = radians(lon1)
  lat2 = radians(lat2)
  lon2 = radians(lon2)

  dlon = lon2 - lon1
  dlat = lat2 - lat1

  a = sin(dlat / 2)**2 + cos(lat1) * cos(lat2) * sin(dlon / 2)**2
  c = 2 * atan2(sqrt(a), sqrt(1 - a))

  return R * c

#Apply distance function to dataframe
df['dist']=list(map(lambda k: getDist(df.loc[k]['lat'],df.loc[k]['lon'],newlat,newlon), df.index))

#This will give all locations within radius of 600 km
df[df['dist']<600]

  location    lat     lon        dist
2       LV  36.16 -115.14  555.511724