## Code copied from: https://gist.github.com/kunanit/eb0723eef653788395bb41c661c1fa86

In [ ]:
import pandas as pd
from sqlalchemy import create_engine

In [58]:

# follows django database settings format, replace with your own settings
DATABASES = {
    'pd':{
        'NAME': 'pd',
        'USER': 'louisdods',
        'PASSWORD': '',
        'HOST': 'localhost',
        'PORT': 5432,
    },
}

# choose the database to use
db = DATABASES['pd']

# construct an engine connection string
engine_string = "postgresql+psycopg2://{user}:@{host}:{port}/{database}".format(
    user = db['USER'],
    password = db['PASSWORD'],
    host = db['HOST'],
    port = db['PORT'],
    database = db['NAME'],
)

# create sqlalchemy engine
engine = create_engine(engine_string)

# read a table from database into pandas dataframe, replace "tablename" with your table name
df = pd.read_sql_table('m',engine)

In [59]:
df

,id,waste_stream,amount,address,city,county,postcode,condition,dimensions,image_link1,image_link2,image_link3,longitude,latitude
0,14,Cycle Stands,14,54 Havil Street,Southwark,Greater London,SE5 7RS,Will have to be removed and some damage may be...,,1,2,,-0.083447,51.475315
1,17,Glazed Partitions,8,54 Havil Street,Southwark,Greater London,SE5 7RS,Will have to be removed very efficiently to av...,,5,6,7,-0.083447,51.475315
2,18,Kitchen Set,2,1 Home Farm,Sywell,Northamptonshire,NN6 0BQ,,,8,9,,-0.795324,52.297066
3,19,Tambour Unit,3,1 Home Farm,Sywell,Northamptonshire,NN6 0BQ,Undamaged,,10,11,12,-0.795324,52.297066
4,20,Task Chair,3,1 Home Farm,Sywell,Northamptonshire,NN6 0BQ,Undamaged,,13,14,15,-0.795324,52.297066
5,21,Paving Slabs,250,College Street,Rotherham,South Yorkshire,S65 1AF,Will depend on amount ordered,,20,21,22,-1.354823,53.431080
6,22,Desk,2,College Street,Rotherham,South Yorkshire,S65 1AF,Will depend on amount ordered,,16,17,,-1.354823,53.431080
7,23,Shelving,2,College Street,Rotherham,South Yorkshire,S65 1AF,Used,,25,26,,-1.354823,53.431080
8,24,Ceiling Tiles,50,54 Havil Street,Southwark,Greater London,SE5 7RS,Used,,3,4,27,-0.083447,51.475315

In [55]:
df = df.drop(df.index[:5])

In [56]:
df

,id,type,name,email,reg_num,address1,city1,county1,postcode1,address2,...,county2,postcode2,address3,city3,county3,postcode3,phone,facebook_link,linkedin_link,website
5,6,Charity,Waste Wise Kids,hello@wastewisekids.org,12352813,"The Manor House, Victors Barns, Northampton Road",Brixworth,Northamptonshire,NN69DQ,,...,Bath and North East Somerset,,,,Bath and North East Somerset,,01614496987,,None,wastewisekids.org

In [57]:
df.to_csv('contact_sheet.csv')

In [46]:
df.to_csv('request_sheet.csv')

In [60]:
df.to_csv('material_sheet.csv')